language: php

cache:
    directories:
        - "$HOME/.composer/cache"
        - "vendor"

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
        - php: 7.2
        - php: nightly

before_script:
    - mkdir -p build/logs
    - composer self-update
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - ./vendor/bin/php-coveralls --no-interaction

after_script:
    - ./vendor/bin/phpstan analyse --level max ./src
